"""Constants for the jk bms ble component."""

CONF_BALANCER = "balancer"
CONF_BALANCING = "balancing"
CONF_CHARGING = "charging"
CONF_DISCHARGING = "discharging"
CONF_HEATING = "heating"
CONF_CHARGING_FLOAT_MODE = "charging_float_mode"
CONF_EMERGENCY = "emergency"
CONF_DISABLE_TEMPERATURE_SENSORS = "disable_temperature_sensors"
CONF_DISPLAY_ALWAYS_ON = "display_always_on"
CONF_SMART_SLEEP = "smart_sleep"
CONF_TIMED_STORED_DATA = "timed_stored_data"
CONF_DISABLE_PCL_MODULE = "disable_pcl_module"
