"""Constants for the jk bms ble component."""
CONF_STATUS_BALANCING = "status_balancing"
CONF_STATUS_ONLINE = "status_online"
CONF_STATUS_PRECHARGING = "status_precharging"
CONF_STATUS_CHARGING = "status_charging"
CONF_STATUS_DISCHARGING = "status_discharging"
CONF_STATUS_HEATING = "status_heating"


CONF_BALANCING = "balancing"
CONF_PRECHARGING = "precharging"
CONF_CHARGING = "charging"
CONF_DISCHARGING = "discharging"
CONF_HEATING = "heating"


CONF_CHARGING_FLOAT_MODE = "charging_float_mode"
CONF_TIMED_STORE_DATA = "timed_stored_data"
CONF_EMERGENCY = "emergency"
CONF_DISABLE_TEMPERATURE_SENSORS = "disable_temperature_sensors"
CONF_DISPLAY_ALWAYS_ON = "display_always_on"
CONF_SMART_SLEEP_ON = "smart_sleep_on"
CONF_SMART_SLEEP_TIME = "smart_sleep_time"
CONF_TIMED_STORED_DATA = "timed_stored_data"
CONF_DISABLE_PCL_MODULE = "disable_pcl_module"

CONF_ALARM_WIRERES = "alarm_wireres"
CONF_ALARM_MOSOTP = "alarm_mosotp"
CONF_ALARM_CELLQUANTITY = "alarm_cellquantity"
CONF_ALARM_CURSENSORERR = "alarm_cursensorerr"
CONF_ALARM_CELLOVP = "alarm_cellovp"
CONF_ALARM_BATOVP = "alarm_batovp"
CONF_ALARM_CHOCP = "alarm_chocp"
CONF_ALARM_CHSCP = "alarm_chscp"
CONF_ALARM_CHOTP = "alarm_chotp"
CONF_ALARM_CHUTP = "alarm_chutp"
CONF_ALARM_CPUAUXCOMMUERR = "alarm_cpuauxcommuerr"
CONF_ALARM_CELLUVP = "alarm_celluvp"
CONF_ALARM_BATUVP = "alarm_batuvp"
CONF_ALARM_DCHOCP = "alarm_dchocp"
CONF_ALARM_DCHSCP = "alarm_dchscp"
CONF_ALARM_DCHOTP = "alarm_dchotp"
CONF_ALARM_CHARGEMOS = "alarm_chargemos"
CONF_ALARM_DISCHARGEMOS = "alarm_dischargemos"
CONF_ALARM_GPSDISCONNETED = "alarm_gpsdisconneted"
CONF_ALARM_MODIFYPWDINTIME = "alarm_modifypwdintime"
CONF_ALARM_DISCHARGEONFAILED = "alarm_dischargeonfailed"
CONF_ALARM_BATTERYOVERTEMP = "alarm_batteryovertemp"
CONF_ALARM_TEMPERATURESENSORANOMALY = "alarm_temperaturesensoranomaly"
CONF_ALARM_PLCMODULEANOMALY = "alarm_plcmoduleanomaly"

CONF_ALARM_MOSTEMPSENSORABSENT = "alarm_mostempsensorabsent"
CONF_ALARM_BATTEMPSENSOR1ABSENT = "alarm_battempsensor1absent"
CONF_ALARM_BATTEMPSENSOR2ABSENT = "alarm_battempsensor2absent"
CONF_ALARM_BATTEMPSENSOR3ABSENT = "alarm_battempsensor3absent"
CONF_ALARM_BATTEMPSENSOR4ABSENT = "alarm_battempsensor4absent"
CONF_ALARM_BATTEMPSENSOR5ABSENT = "alarm_battempsensor5absent"