"""Constants for the jk bms component."""

CONF_BALANCER = "balancer"
CONF_PRECHARGING = "precharging"
CONF_CHARGING = "charging"
CONF_DISCHARGING = "discharging"
CONF_DISPLAY_ALWAYS_ON = "display_always_on"
CONF_EMERGENCY = "emergency"
CONF_HEATING = "heating"
CONF_CHARGING_FLOAT_MODE = "charging_float_mode"
